### ISSUE TITLE
panicked at 'byte index 1 is not a char boundary; it is inside '\u{1}' (bytes 0..1)

### ISSUE THREAD

**Issue by jedisct1** [danburkert/prost#66]
Hi there!

Looks like a regression recently happened. Not sure if rustc is to blame (this is with 1.24.0-nightly from 2018-01-03) or if it is a bug in prost.

Here's a trivial proto file:

```
syntax = "proto3";

package edgedns.cli;

message Command {
    message ServiceLoad {
        string service_id = 1;
        string library_path = 2;
    }
    message ServiceUnload {
        string service_id = 1;
    }
    oneof action {
        ServiceLoad service_load = 1;
        ServiceUnload service_unload = 2;
    }
}
```

And an impressive `build.rs` file:
```rust
extern crate prost_build;

fn main() {
    prost_build::compile_protos(&["src/edgedns-cli.proto"], &["src/"]).unwrap();
}
```

That sadly fails with:
```txt
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '\u{0}' (bytes 0..1) of `���������dp|�������M��-��-���-��-�@�@8 H�@H�@�@	�|���	�|���]R�P�A�}�������|���`[...]', src/libcore/str/mod.rs:2234:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49

...

  12: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index
             at /Users/travis/build/rust-lang/rust/src/libcore/str/mod.rs:1987
  13: core::str::traits::<impl core::ops::index::Index<core::ops::range::RangeFrom<usize>> for str>::index
             at /Users/travis/build/rust-lang/rust/src/libcore/str/mod.rs:1734
  14: unicode_segmentation::word::UWordBounds::get_next_cat
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-segmentation-1.2.0/src/word.rs:611
  15: <unicode_segmentation::word::UWordBounds<'a> as core::iter::iterator::Iterator>::next
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-segmentation-1.2.0/src/word.rs:227
  16: <&'a mut I as core::iter::iterator::Iterator>::next
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/iterator.rs:2380
  17: <core::iter::Filter<I, P> as core::iter::iterator::Iterator>::next
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/mod.rs:1362
  18: <unicode_segmentation::word::UnicodeWords<'a> as core::iter::iterator::Iterator>::next
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-segmentation-1.2.0/src/word.rs:30
  19: heck::transform
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.3.0/src/lib.rs:81
  20: <str as heck::camel::CamelCase>::to_camel_case::{{closure}}
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.3.0/src/snake.rs:37
  21: prost_build::ident::to_snake
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/ident.rs:8
  22: core::ops::function::FnMut::call_mut
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:146
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:271
  24: <core::option::Option<T>>::map
             at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:404
  25: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/mod.rs:1251
  26: <core::iter::Chain<A, B> as core::iter::iterator::Iterator>::next
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/mod.rs:758
  27: <core::iter::Chain<A, B> as core::iter::iterator::Iterator>::next
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/mod.rs:754
  28: itertools::Itertools::join
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.6.5/src/lib.rs:1203
  29: prost_build::code_generator::CodeGenerator::resolve_ident
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/code_generator.rs:574
  30: prost_build::code_generator::CodeGenerator::resolve_type
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/code_generator.rs:551
  31: prost_build::code_generator::CodeGenerator::append_oneof
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/code_generator.rs:379
  32: prost_build::code_generator::CodeGenerator::append_message
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/code_generator.rs:215
  33: prost_build::code_generator::CodeGenerator::generate
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/code_generator.rs:94
  34: <core::str::Split<'a, P> as core::iter::traits::DoubleEndedIterator>::next_back
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/lib.rs:342
  35: prost_build::Config::compile_protos
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/lib.rs:321
  36: prost_build::compile_protos
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.2.3/src/lib.rs:401
  37: build_script_build::main
             at ./build.rs:4
  38: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  39: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:480
  40: backtrace_vector_release
             at src/libpanic_unwind/lib.rs:101
  41: std::sys_common::gnu::libbacktrace::init_state
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:365
             at src/libstd/rt.rs:58
  42: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  43: build_script_build::main
```

Any idea?

**Comment by jedisct1** [comment]
This happens with all nightly versions after `2017-12-31`.

**Comment by danburkert** [comment]
Wow, thanks for the report.  Looks like @vorner reported this in parallel in #65, which links to rust-lang/rust#47175.  So it appears to be a rustc bug.

**Comment by danburkert** [comment]
This has been fixed in about the last week or so worth of nightlies, so I'm going to close.
